// Catálogo completo de certidões que o painel de Certidões (/app/certidoes)
// pretende oferecer — 302 documentos, um por órgão emissor real (cartório de
// imóvel, cada Tribunal de Justiça estadual, cada TRT/TRF, Receita Federal,
// Caixa/FGTS, protesto, junta comercial etc). Gerado a partir do catálogo
// público da RevoluTI (mesmos tipos de documento existem em qualquer
// concorrente do setor — não é conteúdo proprietário, é a lista real de
// certidões que existem no Brasil).
//
// `status` reflete o progresso REAL de integração, não é decorativo:
//   'disponivel'    — já buscável de verdade pelo painel
//   'em_construcao' — sendo integrado agora (próximo passo: CND Federal e
//                     FGTS, via API oficial do governo/Serpro)
//   'planejado'     — ainda não iniciado
// Atualizar esse status é o critério de "o que já está funcionando" pedido
// pelo Renato (ago/2026) — plano é ir estado por estado, começando por SP,
// depois RJ, depois SC.
module.exports = [
  { "nome": "FUNESBOM - Certidão Negativa de Débitos", "tipo": "IMÓVEL", "uf": "RJ", "status": "planejado" },
  { "nome": "Matrícula do Imóvel (Certidão ou Visualização)", "tipo": "IMÓVEL", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "Pref. RJ - Certidão de Situação Fiscal e Enfitêutica do Imóvel", "tipo": "IMÓVEL", "uf": "RJ", "status": "planejado" },
  { "nome": "Pref. SJC - Certidão de Dados Cadastrais", "tipo": "IMÓVEL", "uf": "SP", "status": "planejado" },
  { "nome": "Pref. SJC - Certidão de Débitos Municipais", "tipo": "IMÓVEL", "uf": "SP", "status": "planejado" },
  { "nome": "Pref. SP - Certidão Conjunta de Tributos Imobiliários", "tipo": "IMÓVEL", "uf": "SP", "status": "planejado" },
  { "nome": "Pref. SP - Certidão de Dados Cadastrais", "tipo": "IMÓVEL", "uf": "SP", "status": "planejado" },
  { "nome": "Pref. SP - Consulta Débitos de IPTU", "tipo": "IMÓVEL", "uf": "SP", "status": "planejado" },
  { "nome": "Pref. SP - Valor Venal", "tipo": "IMÓVEL", "uf": "SP", "status": "planejado" },
  { "nome": "RFB - CND De Imóvel Rural", "tipo": "IMÓVEL", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "SICAR - Demonstrativo do CAR", "tipo": "IMÓVEL", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "SNCR - Emissão do Certificado de Cadastro do Imóvel Rural (CCIR)", "tipo": "IMÓVEL", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "Secretaria do Patrimônio da União - Certidão de Situação de Ocupação/Aforamento", "tipo": "IMÓVEL", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "TJRJ - Certidão de Dist. Fazendaria do Imóvel", "tipo": "IMÓVEL", "uf": "RJ", "status": "planejado" },
  { "nome": "Transcrição do Imóvel", "tipo": "IMÓVEL", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "CADESP - Consulta Certidão de Situação Cadastral (CNPJ)", "tipo": "CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "CENPROT - Central Nacional de Protesto", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "CENPROT SP - Central de Protesto do Estado de SP", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "CVM - Processos Administrativos Sancionadores", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "Consulta Serasa", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "FGTS - Certificado de Regularidade (CNPJ)", "tipo": "CNPJ", "uf": "NACIONAL", "status": "em_construcao" },
  { "nome": "Fazenda AC - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "AC", "status": "planejado" },
  { "nome": "Fazenda AL - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "AL", "status": "planejado" },
  { "nome": "Fazenda AM - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "AM", "status": "planejado" },
  { "nome": "Fazenda AP - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "AP", "status": "planejado" },
  { "nome": "Fazenda BA - Certidão Negativa", "tipo": "CPF/CNPJ", "uf": "BA", "status": "planejado" },
  { "nome": "Fazenda CE - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "CE", "status": "planejado" },
  { "nome": "Fazenda DF - Certidão Negativa", "tipo": "CPF/CNPJ", "uf": "DF", "status": "planejado" },
  { "nome": "Fazenda DF - Certidão de Dívida Ativa", "tipo": "CPF/CNPJ", "uf": "DF", "status": "planejado" },
  { "nome": "Fazenda ES - Certidão Negativa", "tipo": "CPF/CNPJ", "uf": "ES", "status": "planejado" },
  { "nome": "Fazenda GO - Certidão Negativa", "tipo": "CPF/CNPJ", "uf": "GO", "status": "planejado" },
  { "nome": "Fazenda MA - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "MA", "status": "planejado" },
  { "nome": "Fazenda MG - Certidão de Débitos Tributários", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "Fazenda MS - Certidão Negativa", "tipo": "CPF/CNPJ", "uf": "MS", "status": "planejado" },
  { "nome": "Fazenda MT - Certidão de Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "MT", "status": "planejado" },
  { "nome": "Fazenda PB - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "PB", "status": "planejado" },
  { "nome": "Fazenda PE - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "PE", "status": "planejado" },
  { "nome": "Fazenda PR - Certidão Negativa", "tipo": "CPF/CNPJ", "uf": "PR", "status": "planejado" },
  { "nome": "Fazenda RJ - Certidão de Regularidade Fiscal", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "Fazenda RN - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "RN", "status": "planejado" },
  { "nome": "Fazenda RO - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "RO", "status": "planejado" },
  { "nome": "Fazenda RR - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "RR", "status": "planejado" },
  { "nome": "Fazenda RS - Certidão de Situação Fiscal", "tipo": "CPF/CNPJ", "uf": "RS", "status": "planejado" },
  { "nome": "Fazenda SC - Certidão Negativa", "tipo": "CPF/CNPJ", "uf": "SC", "status": "planejado" },
  { "nome": "Fazenda SE - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "SE", "status": "planejado" },
  { "nome": "Fazenda SP - CADIN", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "Fazenda SP - Certidão de Débitos Tributários Não Inscritos em Dívida Ativa", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "Fazenda TO - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "TO", "status": "planejado" },
  { "nome": "IBAMA - Certidão Negativa de Débito", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "IBAMA - Certidão de Embargos", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "IBAMA - Certificado de Regularidade", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "JUCESP - Ficha Cadastral Completa (CNPJ)", "tipo": "CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "JUCESP - Ficha Cadastral Simplificada (CNPJ)", "tipo": "CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "MPE de São Paulo - Certidão Criminal", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "MPE de São Paulo - Certidão Cível", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "MPF - Amazônia Protege", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "MPF - Certidão Negativa", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "MPT TRT 1 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "MPT TRT 10 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "DF", "status": "planejado" },
  { "nome": "MPT TRT 11 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "AM", "status": "planejado" },
  { "nome": "MPT TRT 12 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "SC", "status": "planejado" },
  { "nome": "MPT TRT 13 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "PB", "status": "planejado" },
  { "nome": "MPT TRT 14 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "RO", "status": "planejado" },
  { "nome": "MPT TRT 15 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "MPT TRT 16 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "MA", "status": "planejado" },
  { "nome": "MPT TRT 17 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "ES", "status": "planejado" },
  { "nome": "MPT TRT 18 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "GO", "status": "planejado" },
  { "nome": "MPT TRT 19 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "AL", "status": "planejado" },
  { "nome": "MPT TRT 2 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "MPT TRT 20 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "SE", "status": "planejado" },
  { "nome": "MPT TRT 21 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "RN", "status": "planejado" },
  { "nome": "MPT TRT 22 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "PI", "status": "planejado" },
  { "nome": "MPT TRT 23 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "MT", "status": "planejado" },
  { "nome": "MPT TRT 24 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "MS", "status": "planejado" },
  { "nome": "MPT TRT 3 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "MPT TRT 4 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "RS", "status": "planejado" },
  { "nome": "MPT TRT 5 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "BA", "status": "planejado" },
  { "nome": "MPT TRT 6 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "PE", "status": "planejado" },
  { "nome": "MPT TRT 7 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "CE", "status": "planejado" },
  { "nome": "MPT TRT 8 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "PA", "status": "planejado" },
  { "nome": "MPT TRT 9 - Certidão Negativa de Feitos", "tipo": "CPF/CNPJ", "uf": "PR", "status": "planejado" },
  { "nome": "MTE - Certidão de Débitos Trabalhistas", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "PGE SP - Certidão de Débitos Tributários da Dívida Ativa", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "Polícia Federal - Certidão de Antecedentes Criminais (CPF)", "tipo": "CPF", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "Pref. Aracaju - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "SE", "status": "planejado" },
  { "nome": "Pref. Boa Vista - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "RR", "status": "planejado" },
  { "nome": "Pref. Campinas - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "Pref. Cuiabá - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "MT", "status": "planejado" },
  { "nome": "Pref. Florianópolis - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "SC", "status": "planejado" },
  { "nome": "Pref. Fortaleza - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "CE", "status": "planejado" },
  { "nome": "Pref. Goiânia - Certidão Negativa", "tipo": "CPF/CNPJ", "uf": "GO", "status": "planejado" },
  { "nome": "Pref. Guarulhos - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "Pref. Macapá - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "AP", "status": "planejado" },
  { "nome": "Pref. Natal - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "RN", "status": "planejado" },
  { "nome": "Pref. Palmas - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "TO", "status": "planejado" },
  { "nome": "Pref. Porto Velho - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "RO", "status": "planejado" },
  { "nome": "Pref. Recife - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "PE", "status": "planejado" },
  { "nome": "Pref. SP - Certidão Conjunta de Débitos de Tributos Mobiliários", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "Pref. Salvador - Certidão Negativa de Débitos (CNPJ)", "tipo": "CNPJ", "uf": "BA", "status": "planejado" },
  { "nome": "Pref. São Luís - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "MA", "status": "planejado" },
  { "nome": "Pref. de Maceió - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "AL", "status": "planejado" },
  { "nome": "Pref. de Manaus - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "AM", "status": "planejado" },
  { "nome": "Pref. de Teresina - Certidão Negativa de Débitos", "tipo": "CPF/CNPJ", "uf": "PI", "status": "planejado" },
  { "nome": "Pref. de Vitoria - CND Tributos Municipais", "tipo": "CPF/CNPJ", "uf": "ES", "status": "planejado" },
  { "nome": "RFB - CND de Tributos Federais", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "em_construcao" },
  { "nome": "RFB - Cartão CNPJ (CNPJ)", "tipo": "CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "RFB - Comprovante de Situação Cadastral no CPF (CPF)", "tipo": "CPF", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "RFB - Consulta Simples Nacional (CNPJ)", "tipo": "CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "RFB - Quadro de Sócios e Administradores (CNPJ)", "tipo": "CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "Pesquisa Nacional de Processos", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "Secretaria de Inspeção do Trabalho - Trabalho Escravo", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "Superior Tribunal de Justiça (STJ) - Certidão Judicial de Distribuição", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "Supremo Tribunal Federal (STF) - Certidão de Distribuição", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "TCU - Consulta Consolidada de Pessoa Jurídica (CNPJ)", "tipo": "CNPJ", "uf": "NACIONAL", "status": "planejado" },
  { "nome": "TJAC - Certidão de Distribuição Criminal de 1º Grau", "tipo": "CPF/CNPJ", "uf": "AC", "status": "planejado" },
  { "nome": "TJAC - Certidão de Distribuição Cível de 1º Grau", "tipo": "CPF/CNPJ", "uf": "AC", "status": "planejado" },
  { "nome": "TJAC - Certidão de Distribuição de Execução Fiscal de 1º Grau", "tipo": "CPF/CNPJ", "uf": "AC", "status": "planejado" },
  { "nome": "TJAC - Certidão de Distribuição de Falência e Recuperação de 1º Grau", "tipo": "CPF/CNPJ", "uf": "AC", "status": "planejado" },
  { "nome": "TJAC - Consulta Processual 1º Grau", "tipo": "CPF/CNPJ", "uf": "AC", "status": "planejado" },
  { "nome": "TJAL - Certidão Dist. Criminal", "tipo": "CPF/CNPJ", "uf": "AL", "status": "planejado" },
  { "nome": "TJAL - Certidão Dist. Execuções Fiscais", "tipo": "CPF/CNPJ", "uf": "AL", "status": "planejado" },
  { "nome": "TJAL - Certidão Dist. de Falência, Insolvência, Rec. Judicial / Extrajudicial e Concordata", "tipo": "CPF/CNPJ", "uf": "AL", "status": "planejado" },
  { "nome": "TJAL - Certidão de Dist. Cível", "tipo": "CPF/CNPJ", "uf": "AL", "status": "planejado" },
  { "nome": "TJAL - Consulta Processual 1º Grau", "tipo": "CPF/CNPJ", "uf": "AL", "status": "planejado" },
  { "nome": "TJAM - Certidão de Dist. Criminal", "tipo": "CPF/CNPJ", "uf": "AM", "status": "planejado" },
  { "nome": "TJAM - Certidão de Dist. Cível", "tipo": "CPF/CNPJ", "uf": "AM", "status": "planejado" },
  { "nome": "TJAM - Certidão de Dist. Falência e Recuperação de Crédito", "tipo": "CPF/CNPJ", "uf": "AM", "status": "planejado" },
  { "nome": "TJAM - Consulta Processual 1º Grau", "tipo": "CPF/CNPJ", "uf": "AM", "status": "planejado" },
  { "nome": "TJAP - Certidão de Dist. Cível e Criminal 1º Grau", "tipo": "CPF/CNPJ", "uf": "AP", "status": "planejado" },
  { "nome": "TJAP - Certidão de Dist. Falência/Recuperação Judicial 1º Grau (CNPJ)", "tipo": "CNPJ", "uf": "AP", "status": "planejado" },
  { "nome": "TJAP - Consulta de Processos de 1º Grau", "tipo": "CPF/CNPJ", "uf": "AP", "status": "planejado" },
  { "nome": "TJBA - Consulta Processual 1º Grau", "tipo": "CPF/CNPJ", "uf": "BA", "status": "planejado" },
  { "nome": "TJBA - Certidão Criminal de 2º Grau", "tipo": "CPF/CNPJ", "uf": "BA", "status": "planejado" },
  { "nome": "TJBA - Certidão Criminal e Exec. Penal de 1º Grau", "tipo": "CPF/CNPJ", "uf": "BA", "status": "planejado" },
  { "nome": "TJBA - Certidão Cível de 1º Grau", "tipo": "CPF/CNPJ", "uf": "BA", "status": "planejado" },
  { "nome": "TJBA - Certidão Cível de 2º Grau", "tipo": "CPF/CNPJ", "uf": "BA", "status": "planejado" },
  { "nome": "TJBA - Certidão Eleitoral de 2º Grau (CPF)", "tipo": "CPF", "uf": "BA", "status": "planejado" },
  { "nome": "TJBA - Certidão de Insolvência de 1º Grau", "tipo": "CPF/CNPJ", "uf": "BA", "status": "planejado" },
  { "nome": "TJBA - Certidão de Interdição, Curatela de 1º Grau (CPF)", "tipo": "CPF", "uf": "BA", "status": "planejado" },
  { "nome": "TJBA - Certidão de Inventário de 1º Grau (CPF)", "tipo": "CPF", "uf": "BA", "status": "planejado" },
  { "nome": "TJBA - Certidão de Recup. Judicial, Falência, Concordata de 1º Grau (CNPJ)", "tipo": "CNPJ", "uf": "BA", "status": "planejado" },
  { "nome": "TJCE - Certidão Dist. Criminal de 1º Grau", "tipo": "CPF/CNPJ", "uf": "CE", "status": "planejado" },
  { "nome": "TJCE - Certidão Dist. Criminal de 2º Grau", "tipo": "CPF/CNPJ", "uf": "CE", "status": "planejado" },
  { "nome": "TJCE - Certidão Dist. Cível de 1º Grau", "tipo": "CPF/CNPJ", "uf": "CE", "status": "planejado" },
  { "nome": "TJCE - Certidão Dist. Cível de 2º Grau", "tipo": "CPF/CNPJ", "uf": "CE", "status": "planejado" },
  { "nome": "TJCE - Processo Judicial Eletrônico (PJE)", "tipo": "CPF/CNPJ", "uf": "CE", "status": "planejado" },
  { "nome": "TJDF - Consulta Processual PJe 1º Grau", "tipo": "CPF/CNPJ", "uf": "DF", "status": "planejado" },
  { "nome": "TJDFT - Certidão de Dist. Criminal de 1º Grau e 2º Grau", "tipo": "CPF/CNPJ", "uf": "DF", "status": "planejado" },
  { "nome": "TJDFT - Certidão de Dist. Cível de 1º Grau e 2º Grau", "tipo": "CPF/CNPJ", "uf": "DF", "status": "planejado" },
  { "nome": "TJDFT - Certidão de Dist. Falência e Concordata", "tipo": "CPF/CNPJ", "uf": "DF", "status": "planejado" },
  { "nome": "TJES - Certidão de Dist. de 1º Grau - Família (CPF)", "tipo": "CPF", "uf": "ES", "status": "planejado" },
  { "nome": "TJES - Certidão de Dist. de 1º Grau - Todas Exceto Família", "tipo": "CPF/CNPJ", "uf": "ES", "status": "planejado" },
  { "nome": "TJES - Consulta Processual PJe 1º Grau", "tipo": "CPF/CNPJ", "uf": "ES", "status": "planejado" },
  { "nome": "TJGO - Certidão de Dist. Criminal PF (CPF)", "tipo": "CPF", "uf": "GO", "status": "planejado" },
  { "nome": "TJGO - Certidão de Dist. Cível PF (CPF)", "tipo": "CPF", "uf": "GO", "status": "planejado" },
  { "nome": "TJGO - Consulta Processual PJe 1º Grau", "tipo": "CPF/CNPJ", "uf": "GO", "status": "planejado" },
  { "nome": "TJMA - Certidão de Ações Cíveis (CPF)", "tipo": "CPF", "uf": "MA", "status": "planejado" },
  { "nome": "TJMA - Certidão de Ações Penais (CPF)", "tipo": "CPF", "uf": "MA", "status": "planejado" },
  { "nome": "TJMA - Certidão de Dist. Falência e Recuperação de Crédito", "tipo": "CPF/CNPJ", "uf": "MA", "status": "planejado" },
  { "nome": "TJMA - Consulta Processual 1º Grau", "tipo": "CPF/CNPJ", "uf": "MA", "status": "planejado" },
  { "nome": "TJMA - Consulta Processual 2º Grau", "tipo": "CPF/CNPJ", "uf": "MA", "status": "planejado" },
  { "nome": "TJMG - Certidão Criminal 1° Instância", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TJMG - Certidão Criminal 2° Instância", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TJMG - Certidão Cível 1° Instância", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TJMG - Certidão Cível 2° Instância", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TJMG - Certidão Vintenária", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TJMG - Certidão de Execução Cível", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TJMG - Certidão de Falência (CNPJ)", "tipo": "CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TJMG - Certidão de Insolvência (CPF)", "tipo": "CPF", "uf": "MG", "status": "planejado" },
  { "nome": "TJMG - Certidão de Tutela/Curatela (CPF)", "tipo": "CPF", "uf": "MG", "status": "planejado" },
  { "nome": "TJMG - Certidão para Fins Eleitorais (CPF)", "tipo": "CPF", "uf": "MG", "status": "planejado" },
  { "nome": "TJMG - Consulta Processual 1º Instância", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TJMG - Consulta Processual 2º Instância", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TJMS - Certidão de Dist. Criminal de 1º Grau", "tipo": "CPF/CNPJ", "uf": "MS", "status": "planejado" },
  { "nome": "TJMS - Certidão de Dist. Cível de 1º Grau", "tipo": "CPF/CNPJ", "uf": "MS", "status": "planejado" },
  { "nome": "TJMS - Certidão de Dist. Falências de 1º Grau", "tipo": "CPF/CNPJ", "uf": "MS", "status": "planejado" },
  { "nome": "TJMS - Consulta Processual 1º Grau", "tipo": "CPF/CNPJ", "uf": "MS", "status": "planejado" },
  { "nome": "TJMT - Certidão de Dist. Criminal de 1º Grau (Pessoa Física)", "tipo": "CPF/CNPJ", "uf": "MT", "status": "planejado" },
  { "nome": "TJMT - Certidão de Dist. Cível de 1º Grau (Pessoa Física)", "tipo": "CPF/CNPJ", "uf": "MT", "status": "planejado" },
  { "nome": "TJMT - Consulta Processual (1º Grau e 2º Grau)", "tipo": "CPF/CNPJ", "uf": "MT", "status": "planejado" },
  { "nome": "TJPA - Certidão Antecedentes Criminais (CPF)", "tipo": "CPF", "uf": "PA", "status": "planejado" },
  { "nome": "TJPA - Certidão Antecedentes Cíveis (CPF)", "tipo": "CPF", "uf": "PA", "status": "planejado" },
  { "nome": "TJPA - Consulta Processual (1º Grau e 2º Grau)", "tipo": "CPF/CNPJ", "uf": "PA", "status": "planejado" },
  { "nome": "TJPB - Certidão de Dist. Criminal", "tipo": "CPF/CNPJ", "uf": "PB", "status": "planejado" },
  { "nome": "TJPB - Certidão de Dist. Criminal de 2° Grau", "tipo": "CPF/CNPJ", "uf": "PB", "status": "planejado" },
  { "nome": "TJPB - Certidão de Dist. Cível", "tipo": "CPF/CNPJ", "uf": "PB", "status": "planejado" },
  { "nome": "TJPB - Certidão de Dist. Cível de 2° Grau", "tipo": "CPF/CNPJ", "uf": "PB", "status": "planejado" },
  { "nome": "TJPB - Certidão de Dist. Execução Fiscal", "tipo": "CPF/CNPJ", "uf": "PB", "status": "planejado" },
  { "nome": "TJPB - Certidão de Dist. Falência (CPF)", "tipo": "CPF", "uf": "PB", "status": "planejado" },
  { "nome": "TJPB - Certidão de Dist. Tutela, Curatela e Interdição", "tipo": "CPF/CNPJ", "uf": "PB", "status": "planejado" },
  { "nome": "TJPB - Consulta Processual 1° Grau", "tipo": "CPF/CNPJ", "uf": "PB", "status": "planejado" },
  { "nome": "TJPE - Certidão de Dist. Antecedente Criminal", "tipo": "CPF/CNPJ", "uf": "PE", "status": "planejado" },
  { "nome": "TJPE - Certidão de Dist. Cível de 1° Grau", "tipo": "CPF/CNPJ", "uf": "PE", "status": "planejado" },
  { "nome": "TJPE - Certidão de Dist. Cível de 2° Grau", "tipo": "CPF/CNPJ", "uf": "PE", "status": "planejado" },
  { "nome": "TJPE - Consulta Processual Unificada (1º Grau e 2º Grau)", "tipo": "CPF/CNPJ", "uf": "PE", "status": "planejado" },
  { "nome": "TJPI - Certidão Negativa Criminal e Auditoria Militar", "tipo": "CPF/CNPJ", "uf": "PI", "status": "planejado" },
  { "nome": "TJPI - Certidão Negativa Cível e Execução Cível", "tipo": "CPF/CNPJ", "uf": "PI", "status": "planejado" },
  { "nome": "TJPI - Certidão Negativa Cível, Execução Cível, Criminal e Auditoria Militar", "tipo": "CPF/CNPJ", "uf": "PI", "status": "planejado" },
  { "nome": "TJPI - Certidão Negativa de Execução Fiscal", "tipo": "CPF/CNPJ", "uf": "PI", "status": "planejado" },
  { "nome": "TJPI - Certidão de Falência, Concordata, Recuperação Judicial e Extrajudicial", "tipo": "CPF/CNPJ", "uf": "PI", "status": "planejado" },
  { "nome": "TJPI - Certidão de Interdição, Curatela e Tutela", "tipo": "CPF/CNPJ", "uf": "PI", "status": "planejado" },
  { "nome": "TJPI - Certidão de Inventário", "tipo": "CPF/CNPJ", "uf": "PI", "status": "planejado" },
  { "nome": "TJPI - Consulta de Processos de 1º Grau", "tipo": "CPF/CNPJ", "uf": "PI", "status": "planejado" },
  { "nome": "TJPR - Consulta Processual 1º Instância", "tipo": "CPF/CNPJ", "uf": "PR", "status": "planejado" },
  { "nome": "TJRJ - Certidão de Dist. Criminais", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TJRJ - Certidão de Dist. Cíveis", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TJRJ - Certidão de Dist. Fazendárias", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TJRJ - Consulta Processual Civel 1º Instância", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TJRJ - Consulta Processual Criminal 1º Instância", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TJRJ - Consulta Processual Dívida Ativa Municipal 1º Instância", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TJRJ - Consulta Processual Empresarial 1º Instância", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TJRJ - Consulta Processual Familia 1º Instância", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TJRJ - Consulta Processual Fazenda Pública 1º Instância", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TJRJ - Consulta Processual de 2º Instância", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TJRN - Certidão de Dist. Antecedentes Criminais", "tipo": "CPF/CNPJ", "uf": "RN", "status": "planejado" },
  { "nome": "TJRN - Certidão de Dist. Ações e Execuções Cíveis e Fiscais", "tipo": "CPF/CNPJ", "uf": "RN", "status": "planejado" },
  { "nome": "TJRN - Certidão de Dist. Falência e/ou Recuperação Judicial e Extrajudicial (CNPJ)", "tipo": "CNPJ", "uf": "RN", "status": "planejado" },
  { "nome": "TJRN - Certidão de Dist. Interdição, Tutela e Curatela (CPF)", "tipo": "CPF", "uf": "RN", "status": "planejado" },
  { "nome": "TJRN - Consulta Processual 1º Grau", "tipo": "CPF/CNPJ", "uf": "RN", "status": "planejado" },
  { "nome": "TJRN - Consulta Processual 2º Grau", "tipo": "CPF/CNPJ", "uf": "RN", "status": "planejado" },
  { "nome": "TJRO - Certidão de Dist. Criminal e Militar", "tipo": "CPF/CNPJ", "uf": "RO", "status": "planejado" },
  { "nome": "TJRO - Certidão de Dist. Cível", "tipo": "CPF/CNPJ", "uf": "RO", "status": "planejado" },
  { "nome": "TJRO - Certidão de Dist. Falências e Recuperações Judiciais", "tipo": "CPF/CNPJ", "uf": "RO", "status": "planejado" },
  { "nome": "TJRO - Consulta de Processos de 1º Grau", "tipo": "CPF/CNPJ", "uf": "RO", "status": "planejado" },
  { "nome": "TJRR - Certidão de Dist. Concordata e Falências", "tipo": "CPF/CNPJ", "uf": "RR", "status": "planejado" },
  { "nome": "TJRR - Certidão de Dist. Criminal", "tipo": "CPF/CNPJ", "uf": "RR", "status": "planejado" },
  { "nome": "TJRR - Certidão de Dist. Cível", "tipo": "CPF/CNPJ", "uf": "RR", "status": "planejado" },
  { "nome": "TJRR - Consulta Processual", "tipo": "CPF/CNPJ", "uf": "RR", "status": "planejado" },
  { "nome": "TJRS - Certidão Judicial Criminal Negativa (CPF)", "tipo": "CPF", "uf": "RS", "status": "planejado" },
  { "nome": "TJRS - Certidão Judicial Cível Negativa de 1º Grau", "tipo": "CPF/CNPJ", "uf": "RS", "status": "planejado" },
  { "nome": "TJRS - Certidão Judicial Cível Negativa de 1º Grau - Execuções Fiscais", "tipo": "CPF/CNPJ", "uf": "RS", "status": "planejado" },
  { "nome": "TJRS - Certidão Judicial Cível Negativa de 1º Grau - Falência (CNPJ)", "tipo": "CNPJ", "uf": "RS", "status": "planejado" },
  { "nome": "TJRS - Certidão Judicial Cível Negativa de 1º Grau - Insolvência civil (CPF)", "tipo": "CPF", "uf": "RS", "status": "planejado" },
  { "nome": "TJRS - Consulta Processual de 1º Instância", "tipo": "CPF/CNPJ", "uf": "RS", "status": "planejado" },
  { "nome": "TJSC - Certidão de Dist. Criminal de 1º Grau", "tipo": "CPF/CNPJ", "uf": "SC", "status": "planejado" },
  { "nome": "TJSC - Certidão de Dist. Criminal de 2º Grau", "tipo": "CPF/CNPJ", "uf": "SC", "status": "planejado" },
  { "nome": "TJSC - Certidão de Dist. Cível de 1º Grau", "tipo": "CPF/CNPJ", "uf": "SC", "status": "planejado" },
  { "nome": "TJSC - Certidão de Dist. Cível de 2º Grau", "tipo": "CPF/CNPJ", "uf": "SC", "status": "planejado" },
  { "nome": "TJSC - Consulta Processual 1º Grau", "tipo": "CPF/CNPJ", "uf": "SC", "status": "planejado" },
  { "nome": "TJSE - Certidão de Distribuição Criminal", "tipo": "CPF/CNPJ", "uf": "SE", "status": "planejado" },
  { "nome": "TJSE - Certidão de Distribuição Cível", "tipo": "CPF/CNPJ", "uf": "SE", "status": "planejado" },
  { "nome": "TJSE - Consulta Processual 1º Grau", "tipo": "CPF/CNPJ", "uf": "SE", "status": "planejado" },
  { "nome": "TJSE - Consulta Processual 2º Grau", "tipo": "CPF/CNPJ", "uf": "SE", "status": "planejado" },
  { "nome": "TJSP - Consulta Processual 1º Grau", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TJSP - Certidão Comarcas e Turmas Recursais Cível - EPROC", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TJSP - Certidão Dist. de Falências, Concordatas e Recuperações", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TJSP - Certidão Dist. de Inventários, Arrolamentos e Testamentos (CPF)", "tipo": "CPF", "uf": "SP", "status": "planejado" },
  { "nome": "TJSP - Certidão de Dist. Cível Em Geral - SAJ", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TJSP - Certidão de Dist. de Ações Criminais", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TJSP - Certidão de Execução Criminal", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TJTO - Certidão de Dist. Criminal", "tipo": "CPF/CNPJ", "uf": "TO", "status": "planejado" },
  { "nome": "TJTO - Certidão de Dist. Cível", "tipo": "CPF/CNPJ", "uf": "TO", "status": "planejado" },
  { "nome": "TJTO - Certidão de Dist. Geral", "tipo": "CPF/CNPJ", "uf": "TO", "status": "planejado" },
  { "nome": "TJTO - Certidão de Dist. Tutela e Curatela", "tipo": "CPF/CNPJ", "uf": "TO", "status": "planejado" },
  { "nome": "TRF 1 - Certidão de Dist. Criminal (1º e 2º grau)", "tipo": "CPF/CNPJ", "uf": "DF", "status": "planejado" },
  { "nome": "TRF 1 - Certidão de Dist. Cível (1º e 2º grau)", "tipo": "CPF/CNPJ", "uf": "DF", "status": "planejado" },
  { "nome": "TRF 2 - Certidão de Dist. Criminal (1º e 2º grau)", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TRF 2 - Certidão de Dist. Cível (1º e 2º grau)", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TRF 3 - Certidão de Dist. Criminal (1º e 2º grau)", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TRF 3 - Certidão de Dist. Cível (1º e 2º grau)", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TRF 3 - Certidão de Dist. Seção Judiciária e JEF de SP Criminal (1º e 2º graus)", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TRF 3 - Certidão de Dist. Seção Judiciária e JEF de SP Cível (1º e 2º graus)", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TRF 3 - Certidão de Dist. Seção Judiciária e JEF do MS Criminal (1º e 2º graus)", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TRF 3 - Certidão de Dist. Seção Judiciária e JEF do MS Cível (1º e 2º graus)", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TRF 3 - Certidão de Dist. TRF da 3ª Região Criminal (1º e 2º graus)", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TRF 3 - Certidão de Dist. TRF da 3ª Região Cível (1º e 2º graus)", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TRF 4 - Certidão de Dist. Criminal (1º e 2º grau)", "tipo": "CPF/CNPJ", "uf": "RS", "status": "planejado" },
  { "nome": "TRF 4 - Certidão de Dist. Cível (1º e 2º grau)", "tipo": "CPF/CNPJ", "uf": "RS", "status": "planejado" },
  { "nome": "TRF 5 - Certidão de Dist. Civel", "tipo": "CPF/CNPJ", "uf": "PE", "status": "planejado" },
  { "nome": "TRF 5 - Certidão de Dist. Criminal", "tipo": "CPF/CNPJ", "uf": "PE", "status": "planejado" },
  { "nome": "TRF 6 - Certidão de Dist. Criminal (1º e 2º grau)", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TRF 6 - Certidão de Dist. Criminal (1º e 2º grau) - EPROC", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TRF 6 - Certidão de Dist. Cível (1º e 2º grau)", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TRF 6 - Certidão de Dist. Cível (1º e 2º grau) - EPROC", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TRF 6 - Certidão de Dist. Eleitoral (1º e 2º grau) - EPROC", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TRT 1 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "RJ", "status": "planejado" },
  { "nome": "TRT 10 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "DF", "status": "planejado" },
  { "nome": "TRT 11 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "AM", "status": "planejado" },
  { "nome": "TRT 12 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "SC", "status": "planejado" },
  { "nome": "TRT 13 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "PB", "status": "planejado" },
  { "nome": "TRT 14 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "RO", "status": "planejado" },
  { "nome": "TRT 15 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TRT 15 - Certidão de Ação Trabalhista (PJE)", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TRT 16 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "MA", "status": "planejado" },
  { "nome": "TRT 17 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "ES", "status": "planejado" },
  { "nome": "TRT 18 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "GO", "status": "planejado" },
  { "nome": "TRT 19 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "AL", "status": "planejado" },
  { "nome": "TRT 2 - Certidão de Ação Trabalhista (PJe)", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TRT 2 - Certidão de Ação Trabalhista (Processos Físicos)", "tipo": "CPF/CNPJ", "uf": "SP", "status": "planejado" },
  { "nome": "TRT 20 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "SE", "status": "planejado" },
  { "nome": "TRT 21 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "RN", "status": "planejado" },
  { "nome": "TRT 22 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "PI", "status": "planejado" },
  { "nome": "TRT 23 - Certidão de Ação Trabalhista (PJE)", "tipo": "CPF/CNPJ", "uf": "MT", "status": "planejado" },
  { "nome": "TRT 24 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "MS", "status": "planejado" },
  { "nome": "TRT 3 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "MG", "status": "planejado" },
  { "nome": "TRT 4 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "RS", "status": "planejado" },
  { "nome": "TRT 5 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "BA", "status": "planejado" },
  { "nome": "TRT 6 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "PE", "status": "planejado" },
  { "nome": "TRT 7 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "CE", "status": "planejado" },
  { "nome": "TRT 8 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "PA", "status": "planejado" },
  { "nome": "TRT 9 - Certidão de Ação Trabalhista", "tipo": "CPF/CNPJ", "uf": "PR", "status": "planejado" },
  { "nome": "TST - Certidão de Negativa Débitos Trabalhistas", "tipo": "CPF/CNPJ", "uf": "NACIONAL", "status": "planejado" }
];
