const fs = require('fs');
const imoveis = JSON.parse(fs.readFileSync('imoveis.json','utf8'));
const arr = Array.isArray(imoveis) ? imoveis : (imoveis.imoveis || []);
const comUser = arr.filter(i => i.userId && i.userId.trim());
const semUser = arr.filter(i => !i.userId || !i.userId.trim());
console.log('Total imoveis:', arr.length);
console.log('Com userId:', comUser.length);
console.log('Sem userId:', semUser.length);
const userIds = [...new Set(comUser.map(i => i.userId))];
console.log('UserIds:', userIds);
